services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-your_root_password}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-lat_lab_db}"
      MYSQL_USER: "${MYSQL_USER:-lat_lab_user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-your_db_password}"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    # 修改为新的入口点路径
    command: ["python", "-m", "src.lat_lab.main"]
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
      - ./backend/plugins:/app/plugins
    environment:
      DB_TYPE: "${DB_TYPE:-mysql}"
      MYSQL_USER: "${MYSQL_USER:-lat_lab_user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-your_db_password}"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      MYSQL_DB: "${MYSQL_DATABASE:-lat_lab_db}"
      SECRET_KEY: "${SECRET_KEY:-}"
      DEBUG: "${DEBUG:-False}"
      BASE_URL: "${BASE_URL:-http://localhost:5173}"
    ports:
      - "45609:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/api
        - VITE_UPLOAD_URL=/uploads
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data: 