services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: lat_lab_db
      MYSQL_USER: lat_lab_user
      MYSQL_PASSWORD: your_db_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend/app:/app/app
    environment:
      MYSQL_USER: lat_lab_user
      MYSQL_PASSWORD: your_db_password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: lat_lab_db
    ports:
      - "45609:8000"
    depends_on:
      - db

volumes:
  db_data: 