"""添加文章审核字段

Revision ID: dc971a6c7670
Revises: 20250813003000A1
Create Date: 2025-09-03 03:27:06.179517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc971a6c7670'
down_revision: Union[str, None] = '20250813003000A1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'is_approved')
    # ### end Alembic commands ###
